/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v0.1.1-mc26.10-56-gb826bf8"
#endif /* AVUTIL_FFVERSION_H */
